INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (1, 'Tiền học phí', '1', '2022', 975000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (2, 'Bảo hiểm y tế', '1', '2022', 120000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (3, 'Bảo hiểm tai nạn', '1', '2022', 40000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (4, 'Tiền vệ sinh', '1', '2022', 40000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (5, 'Quỹ lớp', '1', '2022', 150000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (6, 'Hồ sơ', '1', '2022', 25000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (7, 'Tiền học phí', '2', '2022', 975000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (8, 'Bảo hiểm y tế', '2', '2022', 120000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (9, 'Bảo hiểm tai nạn', '2', '2022', 40000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (10, 'Tiền vệ sinh', '2', '2022', 40000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (11, 'Quỹ lớp', '2', '2022', 150000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (12, 'Hồ sơ', '2', '2022', 25000, 1);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (13, 'Tiền học phí', '1', '2022', 975000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (14, 'Bảo hiểm y tế', '1', '2022', 120000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (15, 'Bảo hiểm tai nạn', '1', '2022', 40000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (16, 'Tiền vệ sinh', '1', '2022', 40000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (17, 'Quỹ lớp', '1', '2022', 150000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (18, 'Hồ sơ', '1', '2022', 25000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (19, 'Tiền học phí', '2', '2022', 975000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (20, 'Bảo hiểm y tế', '2', '2022', 120000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (21, 'Bảo hiểm tai nạn', '2', '2022', 40000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (22, 'Tiền vệ sinh', '2', '2022', 40000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (23, 'Quỹ lớp', '2', '2022', 150000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (24, 'Hồ sơ', '2', '2022', 25000, 2);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (25, 'Tiền học phí', '1', '2022', 1250000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (26, 'Bảo hiểm y tế', '1', '2022', 120000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (27, 'Bảo hiểm tai nạn', '1', '2022', 40000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (28, 'Tiền vệ sinh', '1', '2022', 40000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (29, 'Quỹ lớp', '1', '2022', 150000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (30, 'Hồ sơ', '1', '2022', 25000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (31, 'Tiền học phí', '2', '2022', 975000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (32, 'Bảo hiểm y tế', '2', '2022', 120000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (33, 'Bảo hiểm tai nạn', '2', '2022', 40000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (34, 'Tiền vệ sinh', '2', '2022', 40000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (35, 'Quỹ lớp', '2', '2022', 150000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (36, 'Hồ sơ', '2', '2022', 25000, 3);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (37, 'Tiền học phí', '1', '2022', 975000, 4);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (38, 'Bảo hiểm y tế', '1', '2022', 120000, 4);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (39, 'Bảo hiểm tai nạn', '1', '2022', 40000, 4);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (40, 'Tiền vệ sinh', '1', '2022', 40000, 4);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (41, 'Quỹ lớp', '1', '2022', 150000, 4);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (42, 'Hồ sơ', '1', '2022', 25000, 4);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (43, 'Tiền học phí', '2', '2022', 975000, 4);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (44, 'Bảo hiểm y tế', '2', '2022', 120000, 4);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (45, 'Bảo hiểm tai nạn', '2', '2022', 40000, 4);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (46, 'Tiền vệ sinh', '2', '2022', 40000, 4);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (47, 'Quỹ lớp', '2', '2022', 150000, 4);
INSERT INTO std_management_app.hocphi (MaHocPhi, TenHocPhi, HocKy, NamHoc, TongTien, MaLop) VALUES (48, 'Hồ sơ', '2', '2022', 25000, 4);
