INSERT INTO std_management_app.monhoc (MaMon, TenMonHoc) VALUES (1, 'Toán');
INSERT INTO std_management_app.monhoc (MaMon, TenMonHoc) VALUES (2, 'Vật Lý');
INSERT INTO std_management_app.monhoc (MaMon, TenMonHoc) VALUES (3, 'Hóa Học');
INSERT INTO std_management_app.monhoc (MaMon, TenMonHoc) VALUES (4, 'Tiếng Anh');
INSERT INTO std_management_app.monhoc (MaMon, TenMonHoc) VALUES (5, 'Địa Lý');
INSERT INTO std_management_app.monhoc (MaMon, TenMonHoc) VALUES (6, 'Sinh học');
INSERT INTO std_management_app.monhoc (MaMon, TenMonHoc) VALUES (7, 'Ngữ Văn');
INSERT INTO std_management_app.monhoc (MaMon, TenMonHoc) VALUES (8, 'Lịch Sử');
INSERT INTO std_management_app.monhoc (MaMon, TenMonHoc) VALUES (9, 'GDCD');
INSERT INTO std_management_app.monhoc (MaMon, TenMonHoc) VALUES (10, 'GDQP');
INSERT INTO std_management_app.monhoc (MaMon, TenMonHoc) VALUES (11, 'Thể Dục');
